logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ghksrka3849!
    url: jdbc:mariadb://localhost:3306/sangseung
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: -1
